name: Final Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build APK
        run: |
          # حل مشكلة ملكية المجلد في GitHub Actions
          git config --global --add safe.directory '*'
          
          # تثبيت أدوات البناء
          pip install flet
          
          # إنشاء ملف المتطلبات لضمان وجود مكتبة ephem داخل الهاتف
          echo "flet" > requirements.txt
          echo "ephem" >> requirements.txt
          
          # البدء في عملية بناء الـ APK
          flet build apk --module-name main_android --yes --skip-flutter-doctor

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-final-apk
          path: build/apk/*.apk
