name: Final Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build APK
        run: |
          git config --global --add safe.directory '*'
          pip install flet
          
          # إعداد المكتبات المضمونة والمتاحة في سيرفرات البناء
          echo "skyfield==1.42" > requirements.txt
          echo "jplephem==2.15" >> requirements.txt
          echo "sgp4==2.20" >> requirements.txt
          echo "geopy" >> requirements.txt
          echo "hijri-converter" >> requirements.txt
          echo "arabic-reshaper" >> requirements.txt
          echo "python-bidi" >> requirements.txt
          echo "python-docx" >> requirements.txt
          
          # أمر البناء الموجه لملف البايثون في المجلد الرئيسي
          flet build apk --module-name almequate_android --yes --skip-flutter-doctor

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: almequate-ultimate-apk
          path: build/apk/*.apk
