name: Final Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build APK
        run: |
          git config --global --add safe.directory '*'
          pip install flet
          
          # إنشاء ملف المتطلبات
          echo "flet" > requirements.txt
          echo "ephem" >> requirements.txt
          echo "geopy" >> requirements.txt
          echo "ummalqura" >> requirements.txt
          echo "arabic-reshaper" >> requirements.txt
          echo "python-bidi" >> requirements.txt
          
          # بناء التطبيق - لينكس في جيت هب سيتكفل ببناء ephem
          flet build apk --module-name main_android --yes --skip-flutter-doctor
