name: Final Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

       - name: Build APK
        run: |
          git config --global --add safe.directory '*'
          pip install flet
          
          # استراتيجية التثبيت النظيف: نترك النظام يختار النسخ التي تنجح في التحزيم تلقائياً
          # حذفنا تحديد الإصدارات اليدوي لـ sgp4 و jplephem لمنع التعارض
          echo "skyfield==1.42" > requirements.txt
          echo "arabic-reshaper" >> requirements.txt
          echo "python-bidi" >> requirements.txt
          echo "geopy" >> requirements.txt
          echo "hijri-converter" >> requirements.txt
          
          # أمر البناء المحدث مع تخطي الفحوصات المسببة للفشل
          flet build apk --module-name almequate_android --yes --skip-flutter-doctor



      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: almequate-pro-apk
          path: build/apk/*.apk
